name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: "/home/runner/work/ServerClipboard_API_Solution/ServerClipboard_API_Solution"
  DEPLOY_PATH: "/home/runner/work/ServerClipboard_API_Solution/ServerClipboard_API_Solution"

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current clone project working directory 
        run: |
          pwd
          ls -la

  build:
    needs: environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 01- Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: 02- Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: 03- Build
      run: dotnet build --no-restore
      working-directory: ${{ env.PROJECT_PATH }}

    - name: 04- Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: 05- SPackage Artifacts
      run: |
        mkdir -p ${{ env.DEPLOY_PATH }}/artifacts
        cp -r ${{ env.PROJECT_PATH }}/bin/Release/* ${{ env.DEPLOY_PATH }}/artifacts/
    
    - name: 06- SUpload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ${{ env.DEPLOY_PATH }}/artifacts
