name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current clone project working directory 
        run: |
          echo "----------------------------------------------------------------"
          echo Git Workspace: ${{ github.workspace }}
          echo "----------------------------------------------------------------"
          pwd
          ls -la

  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ${{ github.workspace }}/ServerClipBoard_API_Solution
      PROJECT_PATH: ${{ github.workspace }}/ServerClipBoard_API
      ARTIFACT_PATH: ${{ github.workspace }}/ServerClipBoard_API/Artifact

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/ServerClipBoard_API.csproj
    
    - name: Build
      run: dotnet build --no-restore --configuration Debug ${{ env.PROJECT_PATH }}/ServerClipBoard_API.csproj
    
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.PROJECT_PATH }}/ServerClipBoard_API.csproj
    
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }}/ServerClipBoard_API.csproj -c Release -o ${{ env.ARTIFACT_PATH }}/release
    
    - name: Package Artifacts
      run: |
        echo "------------------------------------------------------"
        echo "Verifying build archives"
        echo "------------------------------------------------------"
        ls -la ${{ env.ARTIFACT_PATH }}/release
        echo "------------------------------------------------------"
        
        echo "Creating temporary Artifact path"
        mkdir -p ${{ env.ARTIFACT_PATH }}
        
        cp -r ${{ env.ARTIFACT_PATH }}/release/* ${{ env.ARTIFACT_PATH }}/
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ${{ env.ARTIFACT_PATH }}
