on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current clone project working directory 
        run: |
          echo
          echo "----------------------------------------------------------------"
          echo Git Workspace: ${{ github.workspace }}
          echo "----------------------------------------------------------------"

          pwd
          ls -la
  
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ${{ github.workspace }}
      PROJECT_PATH: ${{ github.workspace }}/ServerClipboard_API
      BUILD_PATH: ${{ github.workspace }}/ServerClipboard_API/bin/Debug/net8.0
      PUBLISH_PATH: ${{ github.workspace }}/ServerClipboard_API/bin/Release/net8.0/publish/
      ARTIFACT_PATH: ${{ github.workspace }}/ServerClipboard_API/Artifact

    steps:
    
    - name: 01-Checkout repository
      uses: actions/checkout@v4

    - name: 02-Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: 03-Restore dependencies
      run: dotnet restore
      working-directory: ${{ github.workspace }}
    
    - name: 04-Build
      run: dotnet build --no-restore --configuration Debug
      working-directory: ${{ github.workspace }}
    
    - name: 05-Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ github.workspace }}
    
    - name: 06-Publish
      run: |
         ls -la 
         echo
         echo "----------------------------------------------"
         ls -la ${{ env.PROJECT_PATH }}
         
         dotnet publish ${{ env.SOLUTION_PATH }}/ServerClipboard_API/ServerClipboard_API.csproj -c Release
    
    - name: 07-Package Artifacts
      run: |
        echo
        echo "------------------------------------------------------"
        echo "Verifying build archives"
        echo "------------------------------------------------------"
         ls -la ${{ env.PUBLISH_PATH }}
        echo "------------------------------------------------------"
        
        echo "Creating temporary Artifact path"
        mkdir -p ${{ env.ARTIFACT_PATH }}
        
        cp -r ${{ env.BUILD_PATH }}/* ${{ env.ARTIFACT_PATH }}/
    
    - name: 08-Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ env.ARTIFACT_PATH }}
