# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: "/home/runner/work/ServerClipboard/ServerClipboard"
  DEPLOY_PATH: "/home/runner/work/ServerClipboard/ServerClipboard/Deploy"

jobs:
 
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current clone project working directory 
        run: |
          pwd
          ls -la

  build:
    needs: environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      working-directory: ServerClipboard_API_Solution
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ServerClipboard_API_Solution

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ServerClipboard_API_Solution
