name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
# =======================================================================================================================
# VARIAVEIS DE AMBIENTE
# =======================================================================================================================
env:
  PROJECT_PATH: "/home/runner/work/ServerClipboard_API_Solution/ServerClipboard_API_Solution"
  BUILD_PATH: "/home/runner/work/ServerClipboard_API_Solution/ServerClipboard_API_Solution/ServerClipBoard_API/Build"
  ARTIFACT_PATH: "/home/runner/work/ServerClipboard_API_Solution/ServerClipboard_API_Solution/ServerClipBoard_API/Artifact"

jobs:
# =======================================================================================================================
# REFERENCIA DE AMBIENTE
# =======================================================================================================================
  environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current clone project working directory 
        run: |
          pwd
          ls -la
# =======================================================================================================================
# MONTAGEM DO ARTEFATO
# =======================================================================================================================
  build:
    needs: environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 01- Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: 02- Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      working-directory: ${{ env.PROJECT_PATH }}

    - name: Create temporay directories
      run: |
          echo "Create Build & Artifact folders"
          mkdir -p ${{ env.BUILD_PATH }}
          mkdir -p ${{ env.ARTIFACT_PATH }}
    
    - name: 03- Build
      run: dotnet build --no-restore --output ${{ env.BUILD_PATH }}
      working-directory: ${{ env.PROJECT_PATH }}

    - name: 04- Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.PROJECT_PATH }}
    
    - name: 05- Package Artifacts
      run: |
        cp -r ${{ env.BUILD_PATH }}/* ${{ env.ARTIFACT_PATH }}/
    
    - name: 06- Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ${{ env.ARTIFACT_PATH }}
